[versions]
brave-instrumentation = '5.13.7'
brave-opentracing = '1.0.0'
jaeger = '1.8.0'
kotlin = '1.6.0'
kotlin-coroutines = '1.6.0'
opentracing = '0.33.0'
zipkin-reporter = '2.16.3'
opentelemetry = '1.12.0'
opentelemetry-alpha='1.12.0-alpha'

[libraries]
brave-opentracing = { module = 'io.opentracing.brave:brave-opentracing', version.ref = 'brave-opentracing' }
jaeger = { module = 'io.jaegertracing:jaeger-thrift', version.ref = 'jaeger' }
kotlinx-coroutines-core = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-core', version.ref = 'kotlin-coroutines' }
kotlinx-coroutines-reactor = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-reactor', version.ref = 'kotlin-coroutines' }
opentracing = { module = 'io.opentracing:opentracing-api', version.ref = 'opentracing' }
opentracing-util = { module = 'io.opentracing:opentracing-util', version.ref = 'opentracing' }
zipkin-brave-instrumentation = { module = 'io.zipkin.brave:brave-instrumentation-http', version.ref = 'brave-instrumentation' }
zipkin-reporter = { module = 'io.zipkin.reporter2:zipkin-reporter', version.ref = 'zipkin-reporter' }
opentelemetry-api = {module='io.opentelemetry:opentelemetry-api', version.ref ='opentelemetry'}
opentelemetry-sdk = {module='io.opentelemetry:opentelemetry-sdk', version.ref ='opentelemetry'}
opentelemetry-sdk-testing = {module='io.opentelemetry:opentelemetry-sdk-testing', version.ref = 'opentelemetry'}
opentelemetry-sdk-metrics = {module='io.opentelemetry:opentelemetry-sdk-metrics', version.ref = 'opentelemetry-alpha'}
opentelemetry-opentracing-shim = {module='io.opentelemetry:opentelemetry-opentracing-shim', version.ref = 'opentelemetry-alpha'}
opentelemetry-sdk-logs = {module='io.opentelemetry:opentelemetry-sdk-logs', version.ref = 'opentelemetry-alpha'}
opentelemetry-extension-annotations = {module='io.opentelemetry:opentelemetry-extension-annotations', version.ref = 'opentelemetry'}

[plugins]
kotlinjvm = { id = 'org.jetbrains.kotlin.jvm', version.ref = 'kotlin' }
kotlinkapt = { id = 'org.jetbrains.kotlin.kapt', version.ref = 'kotlin' }
